"""Enclave State Registry ABI.

Generated from contracts/esr/EnclaveStateRegistry.abi in the SDK, whose
selectors were verified against the deployed contract.
"""

contract = {
    # Bloxberg mainnet and testnet are the same chain (chainId 8995), so both
    # use this one deployment.
    "address_bloxberg": "0x4f6c0Ae54567CAeD372d265fEF412C2B5ed1302A",
    "abi": [   {   'anonymous': False,
        'inputs': [   {   'indexed': True,
                          'internalType': 'address',
                          'name': 'enclave',
                          'type': 'address'},
                      {   'indexed': True,
                          'internalType': 'bytes32',
                          'name': 'key',
                          'type': 'bytes32'},
                      {'indexed': False, 'internalType': 'string', 'name': 'cid', 'type': 'string'},
                      {   'indexed': False,
                          'internalType': 'uint256',
                          'name': 'version',
                          'type': 'uint256'}],
        'name': 'StateCommitted',
        'type': 'event'},
    {'inputs': [], 'name': 'EmptyCID', 'type': 'error'},
    {   'inputs': [   {'internalType': 'uint256', 'name': 'expected', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'actual', 'type': 'uint256'}],
        'name': 'VersionMismatch',
        'type': 'error'},
    {   'inputs': [   {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'},
                      {'internalType': 'string', 'name': 'newCID', 'type': 'string'},
                      {'internalType': 'uint256', 'name': 'expectedVersion', 'type': 'uint256'}],
        'name': 'commit',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'exists',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'getState',
        'outputs': [   {'internalType': 'string', 'name': 'cid', 'type': 'string'},
                       {'internalType': 'uint256', 'name': 'version', 'type': 'uint256'},
                       {'internalType': 'uint64', 'name': 'updatedAt', 'type': 'uint64'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'getVersion',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'}],
}
