"""Enclave State Registry ABI (nonce-aware enumerable registry).

Generated from contracts/esr/EnclaveStateRegistry.abi in the SDK. On top of
the enumeration API (commitSeq / entryCount / entryAt / getEntriesFrom) this
adds the PUBLIC per-(enclave, key) idempotency nonce: a getNonce view, a
trailing 'nonce' field on StateCommitted, and nonce parameters on
commit / commitFor / commitDigest. The per-key nonce advances by exactly 1
on every commit: 0 = omitted (the registry auto-assigns the next value);
non-zero is client-pinned and must be exactly stored + 1, no gaps, no reuse
(NonceOutOfOrder otherwise).
"""

contract = {
    # Nonce-aware enumerable ESR deployments (2026-08-15), one per network.
    # The on-chain nonce is the primary source of truth (getNonce view),
    # enforced strictly sequentially per key: exactly stored + 1.
    'address_bloxberg': '0x4Bf5cDE3BFD73dd10B707f8B123Ba631D2EBEAD2',
    'address_bloxberg_testnet': '0x0Ea1728EAE108FD3B9340ae91451348E2Cc6b4E4',
    'address_litvm_liteforge': '0x709052Fe77Af543d3d9FE2Ac06a15c635c8D4Be5',
    'abi': [   {'inputs': [], 'name': 'BadSignature', 'type': 'error'},
    {'inputs': [], 'name': 'EmptyCID', 'type': 'error'},
    {   'inputs': [   {'internalType': 'uint256', 'name': 'stored', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'given', 'type': 'uint256'}],
        'name': 'NonceOutOfOrder',
        'type': 'error'},
    {   'inputs': [   {'internalType': 'uint256', 'name': 'expected', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'actual', 'type': 'uint256'}],
        'name': 'RelayNonceMismatch',
        'type': 'error'},
    {   'inputs': [   {'internalType': 'uint256', 'name': 'expected', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'actual', 'type': 'uint256'}],
        'name': 'VersionMismatch',
        'type': 'error'},
    {   'anonymous': False,
        'inputs': [   {   'indexed': True,
                          'internalType': 'address',
                          'name': 'enclave',
                          'type': 'address'},
                      {   'indexed': True,
                          'internalType': 'bytes32',
                          'name': 'key',
                          'type': 'bytes32'},
                      {'indexed': False, 'internalType': 'string', 'name': 'cid', 'type': 'string'},
                      {   'indexed': False,
                          'internalType': 'uint256',
                          'name': 'version',
                          'type': 'uint256'},
                      {   'indexed': False,
                          'internalType': 'uint256',
                          'name': 'seq',
                          'type': 'uint256'},
                      {   'indexed': False,
                          'internalType': 'uint256',
                          'name': 'nonce',
                          'type': 'uint256'}],
        'name': 'StateCommitted',
        'type': 'event'},
    {   'inputs': [   {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'},
                      {'internalType': 'string', 'name': 'newCID', 'type': 'string'},
                      {'internalType': 'uint256', 'name': 'expectedVersion', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'nonce', 'type': 'uint256'}],
        'name': 'commit',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'},
                      {'internalType': 'string', 'name': 'newCID', 'type': 'string'},
                      {'internalType': 'uint256', 'name': 'expectedVersion', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'relayNonce', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'nonce', 'type': 'uint256'}],
        'name': 'commitDigest',
        'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'},
                      {'internalType': 'string', 'name': 'newCID', 'type': 'string'},
                      {'internalType': 'uint256', 'name': 'expectedVersion', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'relayNonce', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'nonce', 'type': 'uint256'},
                      {'internalType': 'bytes', 'name': 'signature', 'type': 'bytes'}],
        'name': 'commitFor',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function'},
    {   'inputs': [],
        'name': 'commitSeq',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [{'internalType': 'uint256', 'name': 'index', 'type': 'uint256'}],
        'name': 'entryAt',
        'outputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                       {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [],
        'name': 'entryCount',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'exists',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'uint256', 'name': 'startIndex', 'type': 'uint256'},
                      {'internalType': 'uint256', 'name': 'limit', 'type': 'uint256'}],
        'name': 'getEntriesFrom',
        'outputs': [   {'internalType': 'address[]', 'name': 'enclaves', 'type': 'address[]'},
                       {'internalType': 'bytes32[]', 'name': 'keys', 'type': 'bytes32[]'},
                       {'internalType': 'string[]', 'name': 'cids', 'type': 'string[]'},
                       {'internalType': 'uint256[]', 'name': 'versions', 'type': 'uint256[]'},
                       {'internalType': 'uint64[]', 'name': 'updatedAts', 'type': 'uint64[]'},
                       {'internalType': 'uint256', 'name': 'total', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'getNonce',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'getState',
        'outputs': [   {'internalType': 'string', 'name': 'cid', 'type': 'string'},
                       {'internalType': 'uint256', 'name': 'version', 'type': 'uint256'},
                       {'internalType': 'uint64', 'name': 'updatedAt', 'type': 'uint64'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'getVersion',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'},
    {   'inputs': [   {'internalType': 'address', 'name': 'enclave', 'type': 'address'},
                      {'internalType': 'bytes32', 'name': 'key', 'type': 'bytes32'}],
        'name': 'relayNonce',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function'}]
}
